"""initial schema

Generated with `alembic revision --autogenerate` against an empty database and
then reviewed: the timestamp defaults were rewritten from the SQLite idiom the
generator emitted to `func.now()`, which is what the models declare.

Revision ID: f689c2ee1256
Revises: 
Create Date: 2026-09-22 18:38:15.446577
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'f689c2ee1256'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_ledger',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('free_spend_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('paid_spend_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_date')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('paid_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('paid_units >= 0', name='paid_units_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('daily_usage',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('formula_gens', sa.Integer(), nullable=False),
    sa.Column('expectation_gens', sa.Integer(), nullable=False),
    sa.Column('analyses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_daily_usage')
    )
    op.create_table('generations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('formula', sa.String(length=8), nullable=False),
    sa.Column('change_type', sa.SmallInteger(), nullable=False),
    sa.Column('change_kind', sa.String(length=1), nullable=False),
    sa.Column('cause_1', sa.String(length=1), nullable=False),
    sa.Column('cause_2', sa.String(length=1), nullable=False),
    sa.Column('paradox_1', sa.Boolean(), nullable=False),
    sa.Column('paradox_2', sa.Boolean(), nullable=False),
    sa.Column('catalogued', sa.Boolean(), nullable=False),
    sa.Column('had_reference', sa.Boolean(), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('characters', sa.String(length=300), nullable=True),
    sa.Column('setting', sa.String(length=100), nullable=True),
    sa.Column('audience', sa.String(length=32), nullable=True),
    sa.Column('user_expectation', sa.Text(), nullable=True),
    sa.Column('adapted_expectation', sa.Text(), nullable=True),
    sa.Column('expectation_adapted', sa.Boolean(), nullable=False),
    sa.Column('override_verdict', sa.String(length=16), nullable=True),
    sa.Column('override_condition', sa.Text(), nullable=True),
    sa.Column('example_seed', sa.Integer(), nullable=False),
    sa.Column('block_b', sa.Text(), nullable=False),
    sa.Column('profile', sa.String(length=16), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('effort', sa.String(length=16), nullable=False),
    sa.Column('units_charged', sa.SmallInteger(), nullable=False),
    sa.Column('was_free', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_formula'), 'generations', ['formula'], unique=False)
    op.create_index('ix_generations_user_created', 'generations', ['user_id', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pack_id', sa.String(length=16), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('telegram_payment_charge_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_payment_charge_id')
    )
    op.create_table('api_calls',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('generation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('effort', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('was_free', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_calls_created', 'api_calls', ['created_at'], unique=False)
    op.create_table('rating_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('generation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name='history_score_range'),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_history_generation_id'), 'rating_history', ['generation_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('generation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name='score_between_1_and_5'),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_id')
    )
    op.create_index('ix_ratings_score', 'ratings', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ratings_score', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_rating_history_generation_id'), table_name='rating_history')
    op.drop_table('rating_history')
    op.drop_index('ix_api_calls_created', table_name='api_calls')
    op.drop_table('api_calls')
    op.drop_table('payments')
    op.drop_index('ix_generations_user_created', table_name='generations')
    op.drop_index(op.f('ix_generations_formula'), table_name='generations')
    op.drop_table('generations')
    op.drop_table('daily_usage')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('budget_ledger')
    # ### end Alembic commands ###
